from django.urls import path
# ...existing imports...

# import the view from the frontend/temp app
from frontend.temp import views as temp_views

# ...existing urlpatterns...
urlpatterns = [
	# ...existing patterns...
	path('portfolio/', temp_views.show_portfolio, name='portfolio'),
	# ...existing patterns...
]
